// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MeuPonto.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class RegistroPontosFeature
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "RegistroPontos.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "Features", "Registro Pontos", "O sistema deverá fornecer para o trabalhador a capacidade de registrar seus ponto" +
                    "s.\r\n\r\nO sistema deverá fornecer para o trabalhador a capacidade de registrar um " +
                    "ponto", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Registro Pontos")))
            {
                await global::MeuPonto.Features.RegistroPontosFeature.FeatureSetupAsync(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[Registrar Ponto] Trabalhador registra os pontos de entrada e saída do expediente" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Registro Pontos")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("main")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("27/11/2022 09:14", "Marcelo - Ateliex", "Entrada", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("27/11/2022 18:05", "Marcelo - Ateliex", "Saida", null)]
        public async System.Threading.Tasks.Task RegistrarPontoTrabalhadorRegistraOsPontosDeEntradaESaidaDoExpediente(string dataHora, string contrato, string momentoId, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "main"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("data/hora", dataHora);
            argumentsOfScenario.Add("contrato", contrato);
            argumentsOfScenario.Add("momento id", momentoId);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[Registrar Ponto] Trabalhador registra os pontos de entrada e saída do expediente" +
                    "", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
 await testRunner.GivenAsync(string.Format("que a data/hora do relógio é \'{0}\'", dataHora), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 14
 await testRunner.AndAsync(string.Format("que existe um contrato aberto \'{0}\'", contrato), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 15
 await testRunner.WhenAsync("o trabalhador solicitar um registro de ponto", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 16
 await testRunner.ThenAsync("o sistema deverá apresentar um ponto novo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "data/hora",
                            "contrato",
                            "momento id"});
                table23.AddRow(new string[] {
                            string.Format("{0}", dataHora),
                            string.Format("{0}", contrato),
                            string.Format("{0}", momentoId)});
#line 17
 await testRunner.WhenAsync("o trabalhador registrar o ponto como:", ((string)(null)), table23, "Quando ");
#line hidden
#line 20
 await testRunner.ThenAsync("o sistema deverá registrar o ponto como esperado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 21
 await testRunner.AndAsync(string.Format("a data do ponto deverá ser \'{0}\'", dataHora), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 22
 await testRunner.AndAsync(string.Format("o ponto deverá ser qualificado pelo contrato \'{0}\'", contrato), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 23
 await testRunner.AndAsync(string.Format("o momento do ponto deverá ser de \'{0}\'", momentoId), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 24
 await testRunner.ButAsync("o ponto não deverá indicar que foi uma pausa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Mas ");
#line hidden
#line 25
 await testRunner.AndAsync("o ponto não deverá indicar que foi estimado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 26
 await testRunner.AndAsync("o ponto não deverá ter uma observação", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[Registrar Ponto] Trabalhador qualifica um ponto com um contrato")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Registro Pontos")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("alter")]
        public async System.Threading.Tasks.Task RegistrarPontoTrabalhadorQualificaUmPontoComUmContrato()
        {
            string[] tagsOfScenario = new string[] {
                    "alter"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[Registrar Ponto] Trabalhador qualifica um ponto com um contrato", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
 await testRunner.GivenAsync("que existe um contrato aberto \'Marcelo - Ateliex\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 38
 await testRunner.AndAsync("que existe um registro de ponto em andamento", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "contrato"});
                table24.AddRow(new string[] {
                            "Marcelo - Ateliex"});
#line 39
 await testRunner.WhenAsync("o trabalhador registrar o ponto como:", ((string)(null)), table24, "Quando ");
#line hidden
#line 42
 await testRunner.ThenAsync("o ponto deverá ser registrado como esperado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[Registrar Ponto] Trabalhador deixa de qualificar um ponto com um contrato")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Registro Pontos")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("alter")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("wip")]
        public async System.Threading.Tasks.Task RegistrarPontoTrabalhadorDeixaDeQualificarUmPontoComUmContrato()
        {
            string[] tagsOfScenario = new string[] {
                    "alter",
                    "wip"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[Registrar Ponto] Trabalhador deixa de qualificar um ponto com um contrato", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 45
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 46
 await testRunner.GivenAsync("que existe um contrato aberto \'Marcelo - Ateliex\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 47
 await testRunner.AndAsync("que existe um registro de ponto em andamento", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "contrato"});
                table25.AddRow(new string[] {
                            "<null>"});
#line 48
 await testRunner.WhenAsync("o trabalhador tentar registrar o ponto como:", ((string)(null)), table25, "Quando ");
#line hidden
#line 51
 await testRunner.ThenAsync("a tentativa de registrar o ponto deverá falhar com um erro \"\'Contrato\' deve ser i" +
                        "nformado.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[Registrar Ponto] Trabalhador registra os pontos de pausa do expediente")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Registro Pontos")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("alter")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("27/11/2022 12:07", "Marcelo - Ateliex", "Saida", "Almoco", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("27/11/2022 13:05", "Marcelo - Ateliex", "Entrada", "Almoco", null)]
        public async System.Threading.Tasks.Task RegistrarPontoTrabalhadorRegistraOsPontosDePausaDoExpediente(string dataHora, string contrato, string momentoId, string pausaId, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "alter"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("data/hora", dataHora);
            argumentsOfScenario.Add("contrato", contrato);
            argumentsOfScenario.Add("momento id", momentoId);
            argumentsOfScenario.Add("pausa id", pausaId);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[Registrar Ponto] Trabalhador registra os pontos de pausa do expediente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
 await testRunner.GivenAsync(string.Format("que existe um contrato aberto \'{0}\'", contrato), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 58
 await testRunner.WhenAsync("o trabalhador solicitar um registro de ponto", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "data/hora",
                            "contrato",
                            "momento id",
                            "pausa id"});
                table26.AddRow(new string[] {
                            string.Format("{0}", dataHora),
                            string.Format("{0}", contrato),
                            string.Format("{0}", momentoId),
                            string.Format("{0}", pausaId)});
#line 59
 await testRunner.AndAsync("o trabalhador registrar o ponto como:", ((string)(null)), table26, "E ");
#line hidden
#line 63
 await testRunner.ThenAsync(string.Format("o momento do ponto deverá ser de \'{0}\'", momentoId), ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 64
 await testRunner.AndAsync(string.Format("a pausa do ponto deverá ser \'{0}\'", pausaId), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[Registrar Ponto] Trabalhador registra o ponto justificando porque chegou atrasad" +
            "o")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Registro Pontos")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("alter")]
        public async System.Threading.Tasks.Task RegistrarPontoTrabalhadorRegistraOPontoJustificandoPorqueChegouAtrasado()
        {
            string[] tagsOfScenario = new string[] {
                    "alter"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[Registrar Ponto] Trabalhador registra o ponto justificando porque chegou atrasad" +
                    "o", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 74
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
 await testRunner.GivenAsync("que existe um contrato aberto", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 76
 await testRunner.AndAsync("que existe um registro de ponto em andamento", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 77
 await testRunner.WhenAsync("o trabalhador registrar o ponto com a seguinte observação:", "Hoje o trânsito estava lento.", ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 82
 await testRunner.ThenAsync("o ponto deverá ser registrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 83
 await testRunner.AndAsync("a observação do ponto deverá ser:", "Hoje o trânsito estava lento.", ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
